### PR TITLE
replace overlayImage by overlayLayer

### PR DESCRIPTION
**Pull request by guillaumerems**
Hi,

I did this update to be able to put a marker over an image.
If you could check and merge it

Thanks ;)

### CODE REVIEW

**Comment by AckerApple** [comment]
Could you give me more details. Why remove overlayImage? And what is overlayLayer.

Please elaborate as I do not have enough context to know what’s going on with your pull request

**Comment by guillaumerems** [comment]
I do want to display a marker over an image.

With overlayImage, the marker is behind the image so we do not see it.
With overlayLayer, the marker is over the image so we can see the marker, and the image below.

**Comment by AckerApple** [comment]
I think I want to keep “overlayImage” and mixin “overlayLayer”.

I forgot what overlayImage does and believe that because it’s just inherited for agm-core marker directive.

Looks like I’m gonna have to look those both up before I blindly accept you code that deletes something.

I’ll be in touch within 6 days I believe

**Comment by AckerApple** [comment]
Sorry, I checked out your code and it fails.

## Issue
- The items in the demo are not clickable
- I revert your code, the demo code works as expected

I checked out your repo, I pulled the branch overlayLayer, and ran the following:
```
$ npm install
$ npm run watch
```

I also don't like this code. I think you should only use the agm-overlay directive for html content. It sounds like you are trying to do both an image and html in just one agm-overlay. Maybe you should use a separate marker?

I think agm-core's *provided* MarkerManager directive does all that it does using overlayImage. This library, agm-overlays, sorta fakes being a marker so that it can work with MarkerManager provider of agm-core.

To close, I have another pull request from someone else I'm moving onto. I think you might be in for some huge changes if you want to use overlayLayer.

Good luck. Rejected, for now

**Comment by AckerApple** [comment]
I accepted the other pull request. Be sure to pull before you work on this further.

I think since you are using overlayLayer, the click action is not being attached.

**Comment by guillaumerems** [comment]
No problem I will keep it on my branch as I must be able to get a marker over an image.

**Pull request closed without merging**
