### PR TITLE
Fix Bug: Stop Propagation

### PR DESCRIPTION
**Pull request by havo07**
Stop Propagation of event 'markerClick' in Overlay with on event 'mapClick' in Map

### CODE REVIEW

**Comment by AckerApple** [comment]
Way too many unnecessary code edits. I'll accept you are new. I don't want most of your text edits. So now I have to take time to cut out the code I do want.

I'll accept this pull request sometime today. If you had only made the fixes, I might have already accepted this request but now I have to edit it.

**Comment by havo07** [comment]
Sorry, my editor adjusted the spaces in automatic according to the norms of writing, in fact only edit 1 line per file.

**Comment by AckerApple** [comment]
Understood. I will accept this request today.

**Comment by havo07** [comment]
Thank you, greetings, excellent work yours helped me a lot in what I needed to generate

**Comment by AckerApple** [comment]
I made just the single change I think you made and published as version 1.4.0

I could not accept this pull request because it made too many unnecessary edits

**Pull request closed without merging**
